### ISSUE TITLE
CI/CD Implementation

### ISSUE THREAD

**Issue by nelsontr** [neiist-dev/neiist-website#239]
Please check out this [🔗 YT Video](https://www.youtube.com/watch?v=6-RtA6FlbgQ) for more detailed information

**TODO**
- [ ] Create a "deploy" branch, with 2 people's approval (for now)
- [ ] Config actions>runner for a self-hosted service
- [ ] Create actions flow script with commands used to update server files (backend+frontend)
- [ ] Config server: nginx, services, etc...

**Comment by nelsontr** [comment]
Took different approach from the video

**Comment by nelsontr** [comment]
PRs about the Issue: #251, #252, #253, #254;
Some issues were treated in master branch.
